import BannerTemplate from "../../components/shared/BannerTemplate";
import Head from "next/head";
import ProductDetails from "../../components/products/ProductDetails";
import React from "react";
import fs from "fs/promises";
import path from "path";

const ProductDetail = ({ product }) => {
  return (
    <>
      <Head>
        <title>{product.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="pt-[75px]">
        <BannerTemplate
          background="/images/The-Advantage-of-Multiple-Pairs-of-Eyewear_SS-Graphic-3-1080x675.jpg"
          header="اطلاعات محصول"
        />
        <ProductDetails product={product} />
      </div>
    </>
  );
};

export async function getStaticProps(context) {
  const productId = context.params.id;
  const filePathed = path.join(process.cwd(), "data", "data.json");
  const getFsData = await fs.readFile(filePathed);
  const data = JSON.parse(getFsData);
  const products = data.products;
  const product = products.find(p => p.id === productId);

  return {
    props: {
      product,
    },
  };
}

export async function getStaticPaths() {
  const filePathed = path.join(process.cwd(), "data", "data.json");
  const getFsData = await fs.readFile(filePathed);
  const data = JSON.parse(getFsData);
  const products = data.products;

  const paths = products.map((product) => ({ params: { id: product.id } }));

  return {
    paths,
    fallback: "blocking",
  };
}

export default ProductDetail;
