import BannerTemplate from "../../components/shared/BannerTemplate";
import Head from "next/head";
import Products from "../../components/products/Products";
import React from "react";
import fs from "fs/promises";
import path from "path";

const index = ({ products }) => {
  return (
    <>
      <Head>
        <title>محصولات</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <BannerTemplate background="/images/5.jpeg" header="محصولات" />
        <Products products={products} />
      </div>
    </>
  );
};

export async function getStaticProps() {
  const filePathed = path.join(process.cwd(), "data", "data.json");
  const getFsData = await fs.readFile(filePathed);
  const data = JSON.parse(getFsData);

  return {
    props: {
      products: data.products,
    },
  };
}
export default index;
