import BannerTemplate from "../components/shared/BannerTemplate";
import Cart from '../components/cart/Cart';
import Head from "next/head";
import React from "react";

const cart = () => {
  return (
    <>
      <Head>
        <title>سبد خرید</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <BannerTemplate background="/images/240_F_284325266_o6X6uWOgPAWibQ65vfNAsYV1UfQkHzNv.jpg" header="سبد خرید" />
        <Cart />
      </div>
    </>
  );
};

export default cart;
