import About from "../components/home/about/About";
import Blogs from "../components/home/blogs/Blogs";
import FeaturedProducts from "../components/home/featured/FeaturedProducts";
import Head from "next/head";
import Questions from "../components/home/questions/Questions";
import Slider from "../components/home/topSlider/Slider";
import Testimonals from "../components/home/testimonals/Testimonals";
import fs from "fs/promises";
import path from "path";
export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Optic Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Slider />
        <About />
        <FeaturedProducts data={data} />
        <Testimonals />
        <Questions />
        <Blogs data={data} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const filePathed = path.join(process.cwd(), "data", "data.json");
  const getFsData = await fs.readFile(filePathed);
  const data = JSON.parse(getFsData);

  return {
    props: {
      data,
    },
  };
}
